#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-obr-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  pipelineRef:
    name: obr-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
    volumes:
    - name: mavengpg
      secret:
        secretName: mavengpg
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-temp
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
