#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: buildutils-build-
  namespace: galasa-tekton
spec:
  params:
  pipelineRef:
    name: buildutils-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-temp
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
