#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-obr-main
  namespace: galasa-tekton
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/galasa-dev/obr
