#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildutils-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
    mountpath: /workspace/git
  params:
  - name: dockerRepo
    type: string
    default: harbor-cicsk8s.hursley.ibm.com
  - name: noPush
    type: string
    default: ""
  steps:
  - name: compile
    workingDir: /workspace/git/buildutils
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - make
  - name: get-commit
    workingDir: /workspace/git/buildutils
    image: $(params.dockerRepo)/galasadev/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git/buildutils/buildutils.githash
      echo commit is $COMMIT
  - name: docker-build
    workingDir: /workspace/git/buildutils/docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/buildutils
    - --destination=$(params.dockerRepo)/galasadev/galasa-buildutilities:latest
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/buildutils/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)/dockerhub
