name: Main build

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

env:
    NAMESPACE: jaydee029
    
jobs:
    build-gradle:
        name: build and Test Extensions 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup JDK 
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'semeru'
            
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 6.9.2
  
            - name: Test and Build Extensions using gradle
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gradle -X sign -b galasa-extensions-parent/build.gradle check publish --scan \
                -PsourceMaven=https://development.galasa.dev/main/maven-repo/framework  \
                -PcentralMaven=https://repo.maven.apache.org/maven2/ \
                -PtargetMaven=https://maven.pkg.github.com/${{env.NAMESPACE}}/extensions/  -PjacocoEnabled=true -PisMainOrRelease=true
              