name: PR build

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  NAMESPACE: jaydee029
  IMAGE_TAG: main
  
jobs:
  build-framework:
    name: Build Framework using openapi2beans and gradle
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            path: obr
      
        - name: Checkout framework
          uses: actions/checkout@v4
          with:
            repository: ${{env.NAMESPACE}}/framework
            path: framework
        
        - name: Checkout managers
          uses: actions/checkout@v4
          with:
            repository: ${{env.NAMESPACE}}/managers
            path: managers
    
        - name: Checkout extensions
          uses: actions/checkout@v4
          with:
            repository: ${{env.NAMESPACE}}/extensions
            path: extensions
        
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'semeru'
            cache: maven
    
        - name: Print githash
          run: |
            echo $GITHUB_SHA > ./maven.githash
        
        - name: Move release.yaml files
          run: |
           mkdir ${{github.workspace}}/obr/galasa-bom/framework && mv ${{github.workspace}}/framework/release.yaml ${{github.workspace}}/obr/galasa-bom/framework
           mkdir ${{github.workspace}}/obr/galasa-bom/managers && mv ${{github.workspace}}/managers/release.yaml ${{github.workspace}}/obr/galasa-bom/managers
           mkdir ${{github.workspace}}/obr/galasa-bom/extensions && mv ${{github.workspace}}/extensions/release.yaml ${{github.workspace}}/obr/galasa-bom/extensions
           mv ${{github.workspace}}/obr/release.yaml ${{github.workspace}}/obr/galasa-bom/

        - name: Set context and run the docker image
          run: |
           docker -v ${{github.workspace}}/obr/galasa-bom:/var/obr/galasa-bom run ghcr.io/${{env.NAMESPACE}}/galasabld-amd64:${{env.IMAGE_TAG}} template --releaseMetadata var/obr/galasa-bom/framework/release.yaml --releaseMetadata /var/obr/galasa-bom/extensions/release.yaml --releaseMetadata /var/obr/galasa-bom/managers/release.yaml --releaseMetadata /var/obr/galasa-bom/release.yaml --template /var/obr/galasa-bom/pom.template --output pom.xml --bom
           cat ${{github.workspace}}/obr/galasa-bom/pom.xml
        

    
    
      