name: PR build

on:
  workflow_dispatch:
  pull_request:
      branches: [main]

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev

jobs:
  build-maven:
    name: Build Maven source code and Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'semeru'
          cache: maven

      - name: Print githash
        run: |
          echo $GITHUB_SHA > ./maven.githash

      - name: Make artefacts directory
        run : |
          mkdir ${{ github.workspace }}/repo
      
      - name: Building Maven source code
        run: |
          mvn -f galasa-maven-plugin/pom.xml deploy -Dgpg.skip=true 
          -Dgalasa.source.repo=https://development.galasa.dev/gh/maven-repo/gradle \
          -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
          -Dgalasa.release.repo=${{ github.workspace }}/repo --batch-mode --errors --fail-at-end 

      - name: Build maven Image for testing
        uses: docker/build-push-action@v5
        with:
            context: .
            file: dockerfiles/dockerfile
            load: true
            tags: maven:test
            build-args: |
              dockerRepository=harbor.galasa.dev
              tag=main